### ISSUE TITLE
Error when initializing latest

### ISSUE THREAD

**Issue by SpuriousSnail86** [steamcore/TinyIpc#13]
**Details**

The version of the TinyIpc library included in the project is 4.1.3 (latest).
The .NET framework ver of the project is 4.8.

**The code throwing the exception is as follows**

`bus  = new TinyIpc.Messaging.TinyMessageBus("MessageBus");`

**The exception shown is as follows**

_Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)_

I have even added this assembly as a reference to the project with the same ver as above, but hasn't fixed.

Let me know if you need any other info to help solve.

**Comment by SpuriousSnail86** [comment]
Hmmm I have confirmed it seems to be working with a .NET framework 7.0 project but on the 4.8 one it throws above exception.

**Comment by DavidZidar** [comment]
Hi, this is not an issue with TinyIpc, it works fine with .NET Framework 4.8, you can verify this yourself by changing `TargetFramework` to `net48` in the ConsoleApp sample project. You seem to have some kind of assembly mismatch or binding redirect issue, I'd use Google and try to find how others solved this problem. I'd also recommend using the SDK style project format rather than the old legacy format as it doesn't have these kinds of problems as much.

**Comment by SpuriousSnail86** [comment]
The exception is only thrown when the code above is called, so its definitely an issue with the library.

My project compiles and runs just fine otherwise.

**Comment by DavidZidar** [comment]
That only means that when you call TinyIpc it loads more assemblies and then you have some kind of conflict that you will have to resolve on your end, there is nothing I can do about that.

**Comment by SpuriousSnail86** [comment]
Iv'e given up trying to fix this and will just use another IPC library
