### ISSUE TITLE
Feature request: allow message receiver return value to PublishAsync caller.

### ISSUE THREAD

**Issue by KaivnD** [steamcore/TinyIpc#14]
Is that possible by add  a `TaskCompletionSource` or someting  to `TinyMessageReceivedEventArgs`, so message receiver can set a result to PublishAsync caller?

**Comment by KaivnD** [comment]
I just make this happen, see #15

**Comment by DavidZidar** [comment]
I'm not sure what you are trying to do, but it doesn't seem right. This is an IPC library, meaning inter *process* communication. The fact that there are two message buses in the same process in the example is just for demonstration purposes, that's not how it's meant to be used.

**Comment by KaivnD** [comment]
@DavidZidar Thanks for reply, You are right, I just try this in my real work, not working, that's just for same process. Here is what I want to achieve: 

I have App1 and App2, they need to invoke each other method, and wait for it return value, for example,
App1 host method `A`, this method will revice some value and  do something then return some value to it's caller, and App2 will to call it wait for it's return value. App2 host some other method for App1 too.

**Comment by DavidZidar** [comment]
I see, that is not what this library is for is out of scope for this project so I won't be implementing that. It is possible to implement some kind of request / response mechanism on top of any message bus but it should not be built into the message bus, especially not this one since it can have any number of clients listening at all times.

**Comment by DavidZidar** [comment]
I'd recommend you use some kind of server / client setup instead if you mean to send messages directly between apps and expect responses as well. Maybe gRPC or just HTTP/REST?

**Comment by KaivnD** [comment]
Thanks for explanation. Now I see, this library is not for this. WebSocket could do the job, but it require a local network port, and small message size, which is not good enough for me. 
So I end's up here to find alternative solution, Since TinyIpc comes with smooth message flow in different process, I'm trying to add TinyIpc to my application, except for calling back with value, everything is just fine.
Thanks anyway.

**Comment by DavidZidar** [comment]
You could create an abstraction with some kind of message envelope that contains a request ID and an additional response-ID which can point back to a particular request, then you could send a message with an ID and wait for an incoming request with the appropriate response ID.

That said there are several things that could go wrong:
* There might not even be anyone receiving the message at the other end so a response might never arrive
* There might be multiple receivers at the other end so multiple responses arrive
* There could be timing issues such that the either the request or the response is dropped because the other process might not be listening at the time (like when the apps are started)

In any case, this is out of scope for this project.
